version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    links:
      - backend
    volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    container_name: backend
    image: node:8
    volumes:
      - ./src:/usr/src/app
      - ./logs:/root/.npm/_logs
    links:
      - redis
      - postgres
    working_dir: /usr/src/app
    environment:
        - REDIS_HOST=redis_container
    command: >
               bash -c "ls -lt &&
               pwd &&
               npm start"
  redis:
    container_name: redis_container
    image: redis:5
    expose:
      - 6379
    volumes:
      - ./data/redis:/data
    restart: always
  postgres:
      container_name: postgres_database
      image: postgres:11
      volumes:
        - "./data/postgres:/var/lib/postgresql/data"
      restart: always
      environment:
        POSTGRES_PASSWORD: Test1234
        POSTGRES_DB: dev_express_loan
        POSTGRES_USER: node_loan_user